### ISSUE TITLE
Andrew & Henrique

### ISSUE THREAD

**Issue by anacrisostomo09** [anacrisostomo09/QMB210-Group1#11]
Andrew & Henrique: 
Did you acquire housing freshman year? 
What year did you not acquire on-campus housing? 
How do you feel about the cost of campus housing compared to off-campus housing options?
Do you feel the cost of your housing is justified by the amenities and services provided?

Please respond to this ticket with your Excel worksheet by 10/6 @5pm

**Comment by henriquenunes27** [comment]
[surveyanalysis2.0.xlsx](https://github.com/user-attachments/files/17271892/surveyanalysis2.0.xlsx)

**Comment by andrewb35** [comment]
[QMB analysis 2.xlsx](https://github.com/user-attachments/files/17299113/QMB.analysis.2.xlsx)
