### ISSUE TITLE
Send the Survey to 10 People

### ISSUE THREAD

**Issue by anacrisostomo09** [anacrisostomo09/QMB210-Group1#5]
Please send the survey to 10 people. 
https://qualtricsxm54f9rkqp4.qualtrics.com/jfe/form/SV_3yGbxgF6UgdWAV8

**Comment by gabrielariza23** [comment]
sent to ten people

**Comment by rachelgregg11** [comment]
Sent to ten people

**Comment by Kailey-joe** [comment]
sent to 10 people

**Comment by MariaPBP** [comment]
sent to ten people

**Comment by RyanFantone4** [comment]
sent to ten people

**Comment by jhmontwaid** [comment]
sent to ten people

**Comment by andrewb35** [comment]
sent to 10 people

**Comment by henriquenunes27** [comment]
Sent to 10 people
