### ISSUE TITLE
Send Ana your excel worksheet by Sunday 22nd @ 7pm

### ISSUE THREAD

**Issue by anacrisostomo09** [anacrisostomo09/QMB210-Group1#7]
Email: anakarina.crisostomo@spartans.ut.edu

**Comment by Kailey-joe** [comment]
[https://spartansut-my.sharepoint.com/:x:/g/personal/kailey_joe_spartans_ut_edu/EWWJFrU1759OvVyg6pk0fI0B0OdnIfcoyiMdPHS9UDVJRA?e=D1hzBG](url)
